services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow"]
      interval: 10s
      retries: 5

  airflow-init:
    image: apache/airflow:2.8.1-python3.10
    entrypoint: bash
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__FERNET_KEY: "IY8FORl90ifp2_nNr2V-kq86191WsSb8enWjXtAamx8="
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
    command: >
      -c "
        pip install -r /requirements.txt &&
        airflow db init &&
        airflow users create --username admin --password admin --firstname Jesus --lastname Garcia --role Admin --email jesusgarciasoriano003@gmail.com ||
        true
      "
    volumes:
      - ./dags:/opt/airflow/dags
      - ./data:/opt/airflow/data
      - ./requirements.txt:/requirements.txt

  airflow-webserver:
    image: apache/airflow:2.8.1-python3.10
    entrypoint: bash
    depends_on:
      airflow-init:
        condition: service_completed_successfully
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__FERNET_KEY: "IY8FORl90ifp2_nNr2V-kq86191WsSb8enWjXtAamx8="
      AIRFLOW__WEBSERVER__SECRET_KEY: "Key061122="
      AIRFLOW__LOGGING__REMOTE_LOGGING: "False"


    ports:
      - "8080:8080"
    command: >
      -c "pip install -r /requirements.txt && airflow webserver"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./data:/opt/airflow/data
      - ./requirements.txt:/requirements.txt

  airflow-scheduler:
    image: apache/airflow:2.8.1-python3.10
    entrypoint: bash
    depends_on:
      airflow-init:
        condition: service_completed_successfully
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__FERNET_KEY: "IY8FORl90ifp2_nNr2V-kq86191WsSb8enWjXtAamx8="
      AIRFLOW__WEBSERVER__SECRET_KEY: "Key061122="
    command: >
      -c "pip install -r /requirements.txt && airflow scheduler"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./data:/opt/airflow/data
      - ./requirements.txt:/requirements.txt

volumes:
  postgres-db-volume: